pipeline {
    agent any

    stages {
        stage('Build') { 
            steps {
                sleep(5)
            }
        }
        stage('Test') { 
            steps {
                sh '''
                ls -lrt
                sleep(5)
                '''

            }
        }
        stage('Deploy') { 
            steps {
                sleep(5)
            }
        }
    }
}